version: '3'
services:
  db:
    image: postgres
    environment:
        - POSTGRES_DB=rails
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=adminadmin1234
        - PGDATA=/var/lib/postgresql/data/db-files/
    volumes:
      - ./postgres/tmp/db:/var/lib/postgresql/data
      - ./postgres/entrypoint:/docker-entrypoint-initdb.d
    ports: 
        - "5432:5432"
  web:
    build: 
        context: ./ruby
    volumes:
      - ./ruby:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
