default: &default
  adapter: postgresql
  encoding: unicode
  host: may66.ddns.net:5432
  username: root
  password: adminadmin1234
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test
